RM-9059 Add content details to exception
re-motion/Framework pull request #1026
Opened 2024-02-08 13:06 UTC by KuJo7

https://re-motion.atlassian.net/browse/RM-9059

2024-02-08 13:47 UTC, MichaelKetting requested changes

2024-02-08 13:47 UTC, MichaelKetting commented on Remotion/Development/Web/UnitTesting/UI/Controls/Rendering/HtmlHelperBase.cs
> +      var text = GetDocumentText().Replace("&nbsp;", "&amp;nbsp;");
Please add a unit test for the new stuff.

2024-02-13 11:35 UTC, KuJo7 commented on Remotion/Development/Web/UnitTesting/UI/Controls/Rendering/HtmlHelperBase.cs
> +        throw new InvalidOperationException(ex.Message + "\nContent: " + text, ex);
I checked with Lukas and we think the inner exception is not necessary here since it doesn't make any difference in this case.

2024-02-13 11:59 UTC, MichaelKetting approved these changes

2024-02-13 11:59 UTC, MichaelKetting commented on Remotion/Development/UnitTests/Web/UnitTesting/UI/Controls/Rendering/HtmlHelperBaseTest.cs
> +          Throws.Exception.With.Message.EqualTo("Data at the root level is invalid. Line 1, position 665.\r\n\r\nContent:\r\n" + c_document + "randomError"));
```suggestion
          Throws.Exception.OfType<XmlException>().With.Message.EqualTo("Data at the root level is invalid. Line 1, position 665.\r\n\r\nContent:\r\n" + c_document + "randomError").And.With.InnerException.IsNull);
```

Note: I think the part with the InnerExcpetion is possible, but I did not acutally try it. If it's not a perfect match, please verify syntax and if it appears to not work at all with the single-line syntax while remaining type safe, we leave it out. The general idea is to document that we intentionally skipped the inner exception

2024-02-13 11:59 UTC, MichaelKetting commented on Remotion/Development/UnitTests/Web/UnitTesting/UI/Controls/Rendering/HtmlHelperBaseTest.cs
> +          Throws.Exception.With.Message.EqualTo("Data at the root level is invalid. Line 1, position 665.\r\n\r\nContent:\r\n" + c_document + "randomError"));
I don't need to recheck it but perhaps ask @Frazerus for a once over when you updated to make sure I didn't miss anything?

2024-02-14 10:37 UTC, merged