Feature/rm 9102 remove scrollbar on resolve border element a
re-motion/Framework pull request #1036
Opened 2024-02-23 10:21 UTC by KuJo7

https://re-motion.atlassian.net/browse/RM-9102

2024-02-23 12:32 UTC, MichaelKetting requested changes
@KuJo7 from reading the code, it loks like BorderELementA and BorderElementB have been completely removed in the test code. If so, the associated images are obsolete and should be deleted. Please verify and if so, remove.

cc @Frazerus in case I missed something.

2024-02-27 09:59 UTC, Frazerus commented
These are currently 2 PRs in one, the ResolveBorderElementB is here: https://github.com/re-motion/Framework/pull/1032

2024-02-27 10:04 UTC, MichaelKetting approved these changes

2024-03-07 13:07 UTC, MichaelKetting requested changes

2024-03-07 13:07 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.IntegrationTests/ScreenshotTest.Shared.cs
> +    public void ResolveBorderElementLeft ()
Should be done like ResolveborderElement in line 301, or, possibly, merged with the other test.
@Frazerus

2024-03-07 14:19 UTC, KuJo7 commented
I found some Screenshots from the other task which also should be deleted. I did this within this task, hope that's fine!

2024-03-08 10:07 UTC, MichaelKetting approved these changes

2024-03-19 12:09 UTC, merged