RM-7836: Replace Rhino.Mocks with Moq in Development
re-motion/Framework pull request #104
Opened 2021-05-21 11:43 UTC by derlistigelurch

2021-05-25 09:05 UTC, iam-mholle requested changes

2021-05-25 09:05 UTC, iam-mholle commented on Remotion/Development/Moq/Properties/AssemblyInfo.cs
> +[assembly: AssemblyFileVersion("1.0.0.0")]
Please add a link to **AssemblyInfoShared.cs** to the project and change the content of this file to similar content as the one in Development.RhinoMocks.

2021-05-31 07:23 UTC, iam-mholle approved these changes

2021-05-31 10:54 UTC, MichaelKetting requested changes

2021-05-31 13:32 UTC, derlistigelurch commented on Remotion/Development/Moq/Development.Moq.csproj
> +    </ProjectReference>
without these dependencies the following usings cannot be resolved

`using Remotion.Development.UnitTesting;`
`using Remotion.Utilities;`
`using Remotion.FunctionalProgramming;`

2021-05-31 13:44 UTC, MichaelKetting commented on Remotion/Development/Moq/Development.Moq.csproj
> +    </ProjectReference>
See below about SetEquals/Equivalent getting inlined. then, those dependencies should go bye-bye.

2021-05-31 13:45 UTC, derlistigelurch commented on SharedSource/Development/Moq/UnitTesting/MoqExtensions.cs
> +    public static bool Equivalent<T> (this IEnumerable<T> actual, IEnumerable<T> expected)
so this class can basically be deleted, because it would be empty after inlining the method, right?

2021-06-01 06:04 UTC, derlistigelurch commented on SharedSource/Development/Moq/UnitTesting/Threading/LockingDecoratorTestHelper.cs
> +    public void ExpectSynchronizedDelegation (Expression<Action<T>> action)
How should this overload look like?🤔
`Setup` needs an expression to work properly therefore i cannot simply replace `Expression<Func<T, TResult>>` with `Func<T, TResult>>`.

2021-06-01 06:56 UTC, MichaelKetting commented on SharedSource/Development/Moq/UnitTesting/Threading/LockingDecoratorTestHelper.cs
> +    public void ExpectSynchronizedDelegation (Expression<Action<T>> action)
`
public void ExpectSynchronizedDelegation (Expression<Action<T>> action) { ExpectSynchronizedDelegation (action, action.Compile()); }
public void ExpectSynchronizedDelegation (Expression<Action<T>> expectAction, Action<T> action) { ...  } `

2021-06-01 13:49 UTC, MichaelKetting approved these changes

2021-06-02 12:06 UTC, merged