RM-8198 Upgrade JetbrainsAnnotations to 2023.3.0
re-motion/Framework pull request #1123
Opened 2024-05-08 09:15 UTC by KuJo7

https://re-motion.atlassian.net/browse/RM-9198

2024-05-15 06:20 UTC, MichaelKetting requested changes
I'm missing the updated C# file.

2024-05-17 12:32 UTC, MichaelKetting requested changes

2024-05-17 12:32 UTC, MichaelKetting commented on SharedSource/Core/ReSharperAnnotations/JetbrainsAnnotations.cs
Or we don't change this file/depenedency in this PR but a separate one. (didn't realize that it's different stuff)

2024-05-17 12:32 UTC, MichaelKetting commented on SharedSource/Core/ReSharperAnnotations/JetbrainsAnnotations.cs
> +  [Conditional("JETBRAINS_ANNOTATIONS")]
please check, I believe you have used "internal+conditonal" instead of only "conditonal".

Please redo.

2024-05-23 10:27 UTC, KuJo7 commented on SharedSource/Core/ReSharperAnnotations/JetbrainsAnnotations.cs
I will do it in a separate PR

2024-05-23 10:59 UTC, MichaelKetting approved these changes

2024-05-23 11:22 UTC, merged