RM-9226   Remove binary serialization usages in re-motion
re-motion/Framework pull request #1154
Opened 2024-06-12 13:04 UTC by KuJo7

https://re-motion.atlassian.net/browse/RM-9226

2024-06-20 11:59 UTC, a-ctor requested changes
Apart from the few files with irrelevant using changes the changes look good. I rebased the branch as our builds were faulty before and there are still failed tests. We need to fix those.

There are also a few places where we need do some work still:

- `DomainObjectMixinCodeGenerationBridge.DummyObjectReference` is unused
- `SerializationInfoConcreteMixinTypeIdentifierDeserializer` is unused -> test was removed but not the class?
- `SerializationInfoConcreteMixinTypeIdentifierSerializer` is unused (except in docs) -> test was removed but not the class?
- There are still some `[SerializableAttribute]` outside of Web/ObjectBinding.Web that we might not want?
- There are still some `[NonSerializedAttribute]` outside of Web/ObjectBinding.Web that we might not want?
- `SerializationCallbackTester<T>` and `ISerializationEventReceiver` is unused
- `CommitValidationClientTransactionExtension` is still `[Serializable]` and has two serialization methods
- `Serializer` usages imply `BinaryFormatter` usage so we might want to check those as well.
- `Assert2.IgnoreIfFeatureSerializationIsDisabled` usages also seem to imply binary formatting

@MichaelKetting can you please look over the comments and the list above to check that my comments make sense?

2024-06-20 11:59 UTC, a-ctor commented on Remotion/Data/DomainObjects.UnitTests/Serialization/DataContainerTest.cs
> -namespace Remotion.Data.DomainObjects.UnitTests.Serialization
I am not sure that we want to delete all of these files in their entirety. Many files also do `[Serializable]` checks, which we might still want? Other files do additional tests that are based of `[Serializable]` so they should probably stay as well?

Paging @MichaelKetting to answer this

2024-06-20 11:59 UTC, a-ctor commented on Remotion/Data/DomainObjects/Queries/Configuration/QueryConfiguration.obsolete.cs
> -using Remotion.Utilities;
reset please

2024-06-20 11:59 UTC, a-ctor commented on Remotion/Web/Core/Doc/include/ExecutionEngine/WxeStep.xml
> -      <note type="inheritinfo">
Since we are in Web I think we want to keep this doc

2024-06-20 11:59 UTC, a-ctor commented on Remotion/Web/Development.WebTesting.TestSite.Shared/GenericTest.aspx
> -<%@ Register tagPrefix="remotion" namespace="Remotion.Web.UI.Controls" assembly="Remotion.Web" %>
reset please

2024-06-20 11:59 UTC, a-ctor commented on Remotion/Web/Development.WebTesting.TestSite.Shared/GenericTest.aspx.designer.cs
> -namespace Remotion.Web.Development.WebTesting.TestSite.Shared {
reset please

2024-06-20 11:59 UTC, a-ctor commented on Remotion/Mixins/Core/Definitions/Building/InterfaceIntroductionDefinitionBuilder.cs
> -      _nonIntroducedInterfaces = new HashSet<Type> { typeof(ISerializable), typeof(IDeserializationCallback), typeof(IInitializableMixin) };
Not sure if we want this. cc @MichaelKetting

2024-06-21 13:50 UTC, MichaelKetting commented
@KuJo7 Discussed with @a-ctor please do the changes @a-ctor noted in his review and those I mentioned that you feel you can do quickly and easily. I'll do the rest of the cleanup myself to avoid a ton of review back-and-forth.

2024-07-23 06:16 UTC, MichaelKetting approved these changes

2024-07-23 06:17 UTC, merged