RM-7838: Replace Rhino.Mocks with Moq in Validation
re-motion/Framework pull request #117
Opened 2021-06-04 12:30 UTC by derlistigelurch

2021-06-08 11:09 UTC, iam-mholle requested changes

2021-06-08 11:24 UTC, MichaelKetting commented on Remotion/Validation/UnitTests/Merging/ObjectValidatorExtractorTest.cs
> +                  addingObjectValidationRuleCollector.Object)).Verifiable();
That's correct. 
```
_logContextMock.Setup (
    mock =>
        mock.ValidatorRemoved (
            addingObjectValidationRuleCollector.Object))
    .Verifiable();
```
or (preferred but depends on required effort)
```
_logContextMock
    .Setup (mock =>
        mock.ValidatorRemoved (
            addingObjectValidationRuleCollector.Object))
    .Verifiable();
```
Note that the second option is still a compromise, but it's an acceptable compromise. 

The following would be the completely correct formatting:
```
_logContextMock
    .Setup (
        mock => mock.ValidatorRemoved (
            addingObjectValidationRuleCollector.Object))
    .Verifiable();
```

2021-06-09 09:34 UTC, derlistigelurch commented on Remotion/Validation/UnitTests/Merging/ObjectValidatorExtractorFactoryTest.cs
> +using Moq.Protected;
no you are right, `Moq.Protected` should only be inserted if used

2021-07-21 13:21 UTC, MichaelKetting approved these changes

2021-07-22 07:20 UTC, merged