Feature/rm 9247 add editorconfig license information instead of licenseheader files
re-motion/Framework pull request #1170
Opened 2024-06-27 08:13 UTC by Frazerus

https://re-motion.atlassian.net/browse/RMTEAM-877

2024-06-27 11:05 UTC, martin-herwich approved these changes

2024-06-28 08:21 UTC, MichaelKetting requested changes
I found a left-over shared-source import in 
Remotion\ObjectBinding\Web.Development.WebTesting.IntegrationTests\App_Packages
after reviwing the list of licenseheader-files.

It's something we can simply switch to using a locally linked usage like it is done with SharedSource/NUnit in the same project. Since we're touching the licenseheader files, it would be great if you could create a ticket and clean this up in the current sprint. Should only take a couple of minutes :)

2024-06-28 08:21 UTC, MichaelKetting commented on SharedSource/Core/SharedSource.Core.csproj
You dropped the ReSharper licenseheader file in share source but not the Apache2.0 licenseheader for the other shared source files / did not add an editor.cofnig for them (Core/Development/UnitTests). It looks like this is an oversight?

2024-07-02 09:24 UTC, Frazerus commented on SharedSource/Core/SharedSource.Core.csproj
Yea, I did not find that license file when looking through with solutionwide search. Weird. Fixed now

2024-07-03 07:59 UTC, MichaelKetting approved these changes

2024-07-03 08:22 UTC, merged