RM-7841: Replace Rhino.Mocks with Moq in Security Manager
re-motion/Framework pull request #119
Opened 2021-06-09 08:06 UTC by derlistigelurch

2021-06-09 09:02 UTC, iam-mholle requested changes

2021-06-09 09:20 UTC, derlistigelurch commented on SecurityManager/Clients.Web.Test.SetupDB/DBUtility.cs
> -
uuups! that was a manual change, I thought the rewriter accidentally inserted a new line and therefore I deleted it

2021-06-09 09:27 UTC, iam-mholle commented on SecurityManager/Core.UnitTests/AclTools/Expansion/AclExpansionHtmlWriterTest.cs
> +          aclExpansionHtmlWriterImplementation.Object, new AclExpansionHtmlWriterSettings()) { CallBase = true };
```suggestion
          aclExpansionHtmlWriterImplementation.Object,
          new AclExpansionHtmlWriterSettings())
          { CallBase = true };
```

2021-06-09 11:27 UTC, derlistigelurch commented on SecurityManager/Core.UnitTests/Domain/AccessControl/AccessEvaluation/SecurityTokenBuilderTest.cs
> +
there was a newline which was accidentaly deleted, and i inserted in the wrong line🤫

2021-06-09 12:25 UTC, iam-mholle approved these changes

2021-06-10 08:19 UTC, MichaelKetting requested changes

2021-06-11 06:07 UTC, derlistigelurch commented on SecurityManager/Core.UnitTests/Domain/OrganizationalStructure/GroupTests/BindableObjectImplementation.cs
> +      searchServiceStub.Setup (stub => stub.Search (group, groupTypeProperty, args.Object)).Returns ((IBusinessObject[]) expected);
no the cast is not needed anymore, therefore it was deleted in the latest commit

2021-06-11 06:29 UTC, derlistigelurch commented on SecurityManager/Core.UnitTests/Domain/SearchInfrastructure/OrganizationalStructure/RolePropertiesSearchServiceTests/SearchPositionWithSecurityChecks.cs
> +      principalStub.Verify();
this is a bug in the rewriter and will be fixed soon, for now i deleted the stub verification manually

2021-06-11 09:21 UTC, MichaelKetting approved these changes

2021-06-11 13:09 UTC, merged