RM-7846 Fix incorrect DatePicker positioning when the root node is scrolled
re-motion/Framework pull request #121
Opened 2021-06-09 10:42 UTC by a-ctor

https://re-motion.atlassian.net/browse/RM-7846

2021-06-10 09:01 UTC, iam-mholle requested changes
As communicated per dm, DatePicker popup can overflow to the right, I think it should snap to the right viewport border in this case, as for all other directions.

2021-06-16 09:25 UTC, iam-mholle approved these changes
Works great
![stay there](https://media.giphy.com/media/fE32y40MKyk0O1EmiD/giphy.gif)

2021-06-16 12:30 UTC, MichaelKetting requested changes

2021-06-16 12:30 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web.Test/IndividualControlTests/Form.aspx
> +        <asp:CheckBox ID="MainContentScrollableCheckBox" runat="server" AutoPostBack="True" Text="Main content scrollable" OnCheckedChanged="MainContentScrollableCheckBox_OnCheckedChanged"/>
I'd like to do a pair-review for the ASPX stuff to see if there're sensible improvement options.

2021-06-21 07:32 UTC, MichaelKetting approved these changes

2021-06-21 09:45 UTC, merged