Bugfix/rm 9414 ios 15 safari bei web controls wird eine falsche textfarbe genutzt
re-motion/Framework pull request #1280
Opened 2024-11-29 09:37 UTC by Frazerus

https://re-motion.atlassian.net/browse/RM-9414

2024-11-29 11:14 UTC, MichaelKetting requested changes
didn't get to novagray yet.

2024-11-29 11:14 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/Common.css
> +  color: var(--color-standard-text); /* not sure about this one */
```suggestion
  color: var(--color-standard-text);
```

2024-11-29 11:14 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/Common.css
> +  color: var(--color-standard-text); /* not sure about this one */
```suggestion
  color: var(--color-standard-text);
```

2024-11-29 11:14 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/Common.css
>    border-radius: var(--remotion-themed-border-radius);
Line 189 etc: we should consider also setting the text-color for select > option, too. am worried about Apple-people ;)

2024-11-29 11:14 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/DropDownMenu.css
> +  color: var(--color-standard-text); /*maybe overkill as we set the color on the label below and the other child colors as well */
```suggestion
```

2024-11-29 11:14 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/SingleView.css
> +  background-color: var(--color-standard-background);
```suggestion
```
It's just an aera where we place our content. we don't want do do colors here.

2024-11-29 11:14 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/WebButton.css
> +  color: black;
css properties please

2024-12-02 07:25 UTC, MichaelKetting commented
@Frazerus I realized, there's a couple spots that should probably also get color in BocList, TabbedMenu, TabbedMultiView, SingleView (you already added color there), FormGrid. I'm not 100% sure about the best setup yet. 
You did suggest we should just do body and since we already have font and font-size set on the body, perhaps. 

Right now, e.g. in BocList, we got some parts where the background color and specific foreground accents are not in sync so this sort of mixing I want to cleanup.

In the next screenshot, the red background and the bright green text color bleeds through from the body style. The dark green background and dark red text are based on the standard colors we assign. 

![image](https://github.com/user-attachments/assets/ca4cb640-e323-440e-8615-25f82dba37db)

2024-12-02 07:57 UTC, Frazerus commented
Fixed some things:
Green/red come from body.

![image](https://github.com/user-attachments/assets/ec02f6cb-d3f3-43bc-9a1e-4b33f606b689)

2024-12-02 08:03 UTC, MichaelKetting commented
@Frazerus  thanks, looks good. The sub-menuitem line in the tabbedmenu should also get a background and font color
![image](https://github.com/user-attachments/assets/656aa1df-39cc-40e9-ac66-1fec00157cb0)

And for the review, I need to verify all parts within BocList are using the correct font and background colors, since the FormGrid is sitting right behind it and could be bleeding through.

2024-12-02 08:17 UTC, Frazerus commented
Here is a screenshot of the formgrid having set background to purple and text to coral:
![image](https://github.com/user-attachments/assets/9ab75495-266a-41b3-90c8-722e97dfd295)

Nothing bleeds through :)

2024-12-02 08:19 UTC, MichaelKetting commented
Lovely, thanks!

2024-12-02 08:22 UTC, Frazerus commented
![image](https://github.com/user-attachments/assets/3f48663f-29ca-4038-be0a-5f170954b294)

2024-12-02 08:25 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/TabbedMenu.css
>  div.tabbedMainMenu div.tabStripTabsPane ul li,
Just a quick review remark based on code:
color-contrast is gray and was only applied on the mainmenu-row, not the submenu-row. I think this changed the coloring?

2024-12-02 08:30 UTC, Frazerus commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/TabbedMenu.css
>  div.tabbedMainMenu div.tabStripTabsPane ul li,
Ah, I didn't notice that. Tahnks!

2024-12-18 14:20 UTC, Frazerus commented
Fixed branch names so a new PR is required: #1284

2024-12-18 14:20 UTC, closed without merging