Feature/rm 9279 replace the SBOM generation with the build script functionality
re-motion/Framework pull request #1282
Opened 2024-12-17 11:45 UTC by Frazerus

2025-01-07 12:26 UTC, a-ctor requested changes

2025-01-07 12:26 UTC, a-ctor commented on Directory.Packages.props
> +    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.11.0" />
Why do we need to bump this dependency?

2025-01-07 12:26 UTC, a-ctor commented on Build/Customizations/Properties.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
This will change the files in the output folder of each project. Do we really need this? I think we should avoid this if possible. If we keep it we should check that that Nuget packages have not changed. The new files might get copied into the Nuget package otherwise.

2025-01-07 12:29 UTC, Frazerus commented on Build/Customizations/Properties.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
We need those files so we have all relevant data in the bin folder. Will check the nuget packages

2025-01-08 15:06 UTC, Frazerus commented on Build/Customizations/Properties.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
The nuget packages seem fine. Did not check all 50 though, but got Web.Core, Core.core and OBW.Core and a few others. I don't think it should be a problem. And since we only have so little nuget dependencies, it's ok.

2025-01-08 15:38 UTC, a-ctor approved these changes

2025-01-09 08:38 UTC, MichaelKetting requested changes

2025-01-09 08:38 UTC, MichaelKetting commented on Build/Customizations/Properties.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
I read the original discussion but I don't understand how an MSBuld property fits into our custimizations section. This isn't intended to import msbuild settings. bit more context, please

2025-01-09 08:38 UTC, MichaelKetting commented on Build/Build.cs
> +      // We do not require github auth because we do not do enough requests for licenses and package infos
Why do we not need to do this here but in the base implementation? I think I saw this somewhere with an acutal user/key. Once I know where and why we needed it there, I can better work with this comment :)

2025-01-09 08:38 UTC, MichaelKetting commented on Build/Build.cs
> +                                };
Recommend moving the comment into the array (at the end). Otherwise it reads as if the array is the test projects blacklist.

2025-01-09 08:41 UTC, Frazerus commented on Build/Build.cs
> +      // We do not require github auth because we do not do enough requests for licenses and package infos
Github requires auth when we send off too many requests to its API. The tool calls the github API in some cases. Since we don't really have that problem as our dependency count is low, we do not need to supply the auth info.

2025-01-09 08:44 UTC, Frazerus commented on Build/Customizations/Properties.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
I just put it there because we want it in all projects and it was the first thing I thought about. I guess shared.build.props is more reasonable?

2025-01-09 08:46 UTC, Frazerus commented on Build/Build.cs
> +      // We do not require github auth because we do not do enough requests for licenses and package infos
We might still want this anyways, but with the budget for this being more or less empty, this was a good corner to cut.

2025-01-09 08:47 UTC, MichaelKetting commented on Build/Build.cs
> +      // We do not require github auth because we do not do enough requests for licenses and package infos
okay, so the whole github-auth story is just to support this usecase but we never actually ran into it with re-motion?

Since we do have the auth information in our build (don't we?), shouldn't we still use github auth and just forget about the whole thing? Otherwise, we risk a future failing build if limits change, many builds run in a short time, etc.

2025-01-09 08:54 UTC, MichaelKetting commented on Build/Customizations/Properties.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
you want to have this in all projects in the solution? Then we should put it into the existing shared-build files (probably shared.build.props, indeed!). Thing is, we actually only need it during nuke-builds, not vs-builds, correct?

I guess it's not really a performance issue for re-motion, but the "problem" would be that the build script doesn't work if it's not set. So it would be nice if the sbom-logic also checks this prerequisite (which is probably not doable?). This means, putting it into the shared build files and adding a comment why it's needed would be sufficient for re-motion. An alternative would be to pass it as a property to the msbuild call. We already pass properties from the build script to msbuild and could add it there. Although, having the same build output layout for vs-build and nuke-build might be helpful, which prefers the shared build files.

Thoughts, beyond just putting it into shared.build.props?

2025-01-09 08:56 UTC, MichaelKetting commented on Build/Build.cs
> +      // We do not require github auth because we do not do enough requests for licenses and package infos
just saw the second comment about budget: if the properties are already available, we should add it (15 minutes or less). if we don't have them, yes, we can add later. As I said, I think we already did them in an earlier iteration, as far as I remember.

2025-01-09 08:58 UTC, MichaelKetting approved these changes
I'll approve this. please check the comments and if you see something you think helpful and budgetary sane, we should do that. otherwise we're done.

2025-01-09 08:58 UTC, MichaelKetting commented on Build/Shared.build.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
The explainatory comment, please, regardless of budget

2025-01-09 09:16 UTC, Frazerus commented on Build/Build.cs
> +      // We do not require github auth because we do not do enough requests for licenses and package infos
I can't find anything about github auth in our buildscript. Even if we had the data immediately available, the way how we do things with the Sbom configuration is not well integrated into the nuke infrastructure as I messed the design up a bit. Will create a ticket to fix and to improve the design. It was a bit unfortunate that my first part in nuke things was done while patrick was not there to tell me how to properly work with the nuke infrastructure.

2025-01-09 09:16 UTC, Frazerus commented on Build/Customizations/Properties.props
> +    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
Time constraints, and it doesn't really matter for vs builds IMO.

2025-01-09 11:56 UTC, merged