RM-7878 The border of BocTextValues & BocMultilineTextValues is cut off in Firefox 89
re-motion/Framework pull request #146
Opened 2021-06-28 13:36 UTC by raffaelfoidl

https://re-motion.atlassian.net/browse/RM-7878?oldIssueView=true

2021-07-07 08:21 UTC, raffaelfoidl commented
The modified Screenshots were simply adjusted to the slightly changed layout:
![image](https://user-images.githubusercontent.com/40166342/124721576-85f41e00-df09-11eb-8a8d-d776eeb7544e.png)
![image](https://user-images.githubusercontent.com/40166342/124721593-8987a500-df09-11eb-8b3d-3d83e73ba474.png)

2021-07-07 08:39 UTC, MichaelKetting requested changes

2021-07-07 08:39 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/Res/Themes/NovaGray/Html/BocDateTimeValue.css
> +    margin-right: 2px;
```suggestion
.mozilla span.bocDateInputWrapper
{
    margin-right: 2px;
```

2021-07-07 08:39 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/Res/Themes/NovaGray/Html/BocAutoCompleteReferenceValue.css
> +.mozilla span.bocAutoCompleteReferenceValueInput
please move down to the other `...Input` entries.

I'll also need to understand the use of margin vs. width vs. padding here. When dealing with inline, margin has very specific semantics and we haven't used it with input elements before so I need to understand why this works compared to other approaches.

2021-07-07 08:39 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/Res/Themes/NovaGray/Html/BocDateTimeValue.css
> +.mozilla span.bocDateInputWrapper {
Please move down to the other `bocDateInputWrapper`.

2021-07-12 08:31 UTC, raffaelfoidl commented
Text:
![image](https://user-images.githubusercontent.com/40166342/125255860-26788280-e2fc-11eb-9ffc-6ea1a9cc2972.png)

MultiLineText:
![image](https://user-images.githubusercontent.com/40166342/125255901-32644480-e2fc-11eb-8512-eb95a6b853b7.png)

DateTime:
![image](https://user-images.githubusercontent.com/40166342/125255932-3b551600-e2fc-11eb-9c1f-1eafe62bac90.png)

AutoComplete:
![image](https://user-images.githubusercontent.com/40166342/125255964-414af700-e2fc-11eb-8cd1-de9feac0a90a.png)

2021-07-20 06:24 UTC, MichaelKetting requested changes

2021-07-20 06:24 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/Res/Themes/NovaGray/Html/BocDateTimeValue.css
> +    margin-right: 2px;
There's a margin-right here.

2021-07-22 08:14 UTC, MichaelKetting approved these changes

2021-07-22 10:50 UTC, merged