RM-8052 ContextAwareTypeUtility.s_fields might not be initialized
re-motion/Framework pull request #219
Opened 2021-10-05 10:13 UTC by derlistigelurch

https://re-motion.atlassian.net/browse/RM-8052
https://re-motion.atlassian.net/browse/RM-8047

2021-10-05 10:34 UTC, iam-mholle approved these changes

2021-10-05 10:34 UTC, iam-mholle commented on Remotion/Core/Core/Reflection/ContextAwareTypeUtility.cs
> +    private static readonly Lazy<Fields> s_lazyFields = new(LazyThreadSafetyMode.ExecutionAndPublication);
```suggestion
    private static readonly Lazy<Fields> s_lazyFields = new (LazyThreadSafetyMode.ExecutionAndPublication);
```

2021-10-05 10:34 UTC, iam-mholle commented
FYI this PR targets the duplication, not the "main" issue which would be https://re-motion.atlassian.net/browse/RM-8047.

2021-10-05 10:50 UTC, MichaelKetting requested changes
Please switch to 8047 for documentation purporses.

The fix itself targets the wrong "level". You need too decouple the intiailization of the members in `Fields`. 

Said another way, TypeDiscoveryConfiguration.Current and TypeResolutionConfiguration.Current must be prevented to execute in the same call. 

See the description in RM-8047

2021-10-07 09:40 UTC, MichaelKetting approved these changes

2021-10-11 09:18 UTC, merged