RM-8014 Opening two Functions with WxeExecutor.ExecuteFunctionExternal seems to do nothing
re-motion/Framework pull request #241
Opened 2021-11-05 12:47 UTC by derlistigelurch

2021-11-08 09:30 UTC, iam-mholle requested changes

2021-11-08 09:30 UTC, iam-mholle commented on Remotion/Web/Core/ExecutionEngine/Infrastructure/WxeExecutor.cs
> +      var key = Guid.NewGuid().ToString();
The code works as intended, I can't think of any bad side effects. As an improvement tho, a new guid is created a few lines above, you could store its string in a variable and reuse it here.

2021-11-08 09:59 UTC, iam-mholle approved these changes

2021-11-11 08:08 UTC, MichaelKetting approved these changes

2021-11-11 13:40 UTC, merged