RM-8121 Change type of WebLinkButton.Text from System.String to Remotion.WebString
re-motion/Framework pull request #250
Opened 2021-11-12 10:30 UTC by derlistigelurch

https://re-motion.atlassian.net/browse/RM-8121

2021-11-15 10:04 UTC, iam-mholle requested changes

2021-11-15 10:04 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebLinkButton.cs
> +        writer.Write (AccessKey, false); // TODO RM-8118: not null assertion
I don't think the suggestion can be applied automatically, please fix in a manual commit.

```suggestion
      if (HasControls())
        base.RenderContents (writer);
      else
        Text.Write(writer);
```

2021-11-15 10:04 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebLinkButton.cs
> +    [Bindable(true)]
```suggestion
```

2021-11-15 10:04 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebLinkButton.cs
> +    [DefaultValue("")]
What about `Description`, `Category`?

2021-11-15 10:04 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebLinkButton.cs
> +        type ??= WebStringType.PlainText;
```suggestion
        var type = (WebStringType?) ViewState[c_webLinkButtonTypeKey] ?? WebStringType.PlainText;
```

2021-11-15 10:26 UTC, derlistigelurch commented on Remotion/Web/Core/UI/Controls/WebLinkButton.cs
> +    private const string c_webLinkButtonTypeKey = c_webLinkButtonTextKey + nameof (WebStringType);
ok, let's take the pattern you used in #247

2021-11-16 08:31 UTC, iam-mholle approved these changes

2021-11-16 09:50 UTC, MichaelKetting approved these changes

2021-11-16 11:33 UTC, merged