RM-8143 Update FormGridManager to remove automatic hotkey support for labels
re-motion/Framework pull request #252
Opened 2021-11-15 09:50 UTC by derlistigelurch

2021-11-15 09:54 UTC, iam-mholle approved these changes

2021-11-15 11:50 UTC, MichaelKetting requested changes

2021-11-15 11:50 UTC, MichaelKetting commented on Remotion/Web/Core/UI/Controls/FormGridManager.cs
>                  label.AccessKey = "";
This part goes away, too. The else was meant to handle the hotkey-scenario and we probably should document a breaking change for the AccessKey behavior but the whole section is no meaningless.

2021-11-16 09:49 UTC, MichaelKetting approved these changes

2021-11-16 12:59 UTC, merged