RM-8138-Change-type-of-text-properties-on-WebTabStrip,-TabbedMultiView,-and-TabbedMenu-from-System.String-to-Remotion.WebString
re-motion/Framework pull request #260
Opened 2021-11-18 09:19 UTC by derlistigelurch

https://re-motion.atlassian.net/browse/RM-8138

2021-11-18 09:58 UTC, iam-mholle requested changes

2021-11-18 09:58 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebTabStripImplementation/Rendering/WebTabRenderer.cs
> +          attributes.Add (HtmlTextWriterAttribute.Accesskey.ToString(), command.AccessKey);
Condition is wrong.

2021-11-18 09:58 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebTab.cs
> +  [Description ("The text displayed in this tab. Use '-' for a separator tab. The value will be HTML encoded.")]
```suggestion
  [Description ("The text displayed in this tab. Use '-' for a separator tab.")]
```

2021-11-18 09:58 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebTab.cs
> +      displayName = Text.ToString(WebStringEncoding.HtmlWithTransformedLineBreaks);
```suggestion
      displayName = Text.ToString();
```

2021-11-18 09:58 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebTabStripImplementation/Rendering/WebTabRenderer.cs
> +        renderingContext.Writer.Write(tab.Text.ToString(WebStringEncoding.HtmlWithTransformedLineBreaks));
```suggestion
        tab.Text.Write(renderingContext.Writer);
```

2021-11-18 09:58 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebTabStripImplementation/Rendering/WebTabRenderer.cs
> +          attributes.Add (HtmlTextWriterAttribute.Accesskey.ToString(), command.AccessKey);
`HtmlTextWriterAttribute.Accesskey.ToString()` vs `nameof (HtmlTextWriterAttribute.Accesskey)`

2021-11-18 09:58 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting.ControlObjects/TabbedMultiViewControlObject.cs
> +          HtmlTextWriterAttribute.Accesskey.ToString());
Why the new parameter? Besides, I think you got something wrong, as this could be replaced with `"AccessKey"`.

2021-11-18 09:58 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting.ControlObjects/WebTabStripTabDefinition.cs
> +    public WebTabStripTabDefinition ([NotNull] string itemID, int index, [NotNull] string title, bool isDisabled, string accessKey)
Null check missing

2021-11-18 10:51 UTC, iam-mholle requested changes

2021-11-18 10:51 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/TabbedMenu.cs
>      [Description ("The text displayed in the status area. The value will not be HTML encoded.")]
```suggestion
    [Description ("The text displayed in the status area.")]
```

2021-11-18 10:51 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/TabbedMenuImplementation/Rendering/MenuTabRenderer.cs
>          if (string.IsNullOrEmpty (command.AccessKey))
Condition is wrong.

2021-11-18 10:51 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/TabbedMenuImplementation/Rendering/TabbedMenuRenderer.cs
>          renderingContext.Writer.Write (renderingContext.Control.StatusText); // Do not HTML encode
```suggestion
        renderingContext.Control.StatusText.Write (renderingContext.Writer);
```

2021-11-18 10:51 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebTabStripImplementation/Rendering/WebTabRenderer.cs
> +        if (string.IsNullOrEmpty (command.AccessKey))
Condition is wrong

2021-11-18 10:51 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting.ControlObjects/TabbedMultiViewControlObject.cs
> +          "AccessKey");
What's the purpose of this argument?

2021-11-18 10:51 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting.ControlObjects/WebTabStripTabDefinition.cs
> +    public WebTabStripTabDefinition ([NotNull] string itemID, int index, [NotNull] string title, bool isDisabled, [NotNull] string accessKey)
Nullcheck is missing

2021-11-18 10:51 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting.ControlObjects/WebTabStripTabDefinition.cs
> +      get { return _accessKey; }
This would either return `string.Empty` or `"AccessKey"` -> please check the origin of the value.

2021-11-18 13:32 UTC, iam-mholle requested changes

2021-11-18 13:32 UTC, iam-mholle commented on Remotion/Web/Core/UI/Controls/WebTabStripImplementation/Rendering/WebTabRenderer.cs
> +          renderingContext.Writer.AddAttribute (DiagnosticMetadataAttributes.Content, HtmlUtility.StripHtmlTags (tab.Text.GetValue()));
```suggestion
          renderingContext.Writer.AddAttribute (DiagnosticMetadataAttributes.Content, HtmlUtility.StripHtmlTags (tab.Text));
```

2021-11-18 13:32 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting.ControlObjects/WebTabStripControlObject.cs
> +          "K");
Why is `"K"` the access key here?

2021-11-18 13:32 UTC, iam-mholle commented on Remotion/Web/Development.WebTesting.ControlObjects/WebTabStripControlObject.cs
> +          "K");
The access key should be parsed from the attribute.

2021-11-18 14:41 UTC, iam-mholle requested changes
`MenuTabRenderer` still has the `.Hotkey` using

2021-11-19 10:13 UTC, iam-mholle approved these changes

2021-11-19 11:00 UTC, MichaelKetting requested changes

2021-11-19 11:00 UTC, MichaelKetting commented on Remotion/Web/UnitTests/Core/UI/Controls/WebTabStripImplementation/Rendering/WebTabStripRendererTest.cs
> +          Assert.That (node.OuterXml, Is.EqualTo(text.ToString(WebStringEncoding.HtmlWithTransformedLineBreaks)));
woulnd't this be better as text.GetValue() since Type=Encoded means we don't to anything?

2021-11-19 12:42 UTC, derlistigelurch commented on Remotion/Web/Core/UI/Controls/WebTab.cs
> +  }
@MichaelKetting

2021-11-19 16:07 UTC, MichaelKetting commented on Remotion/Web/Core/UI/Controls/WebTab.cs
> +  }
Ah, you mean the attributes? yes, please.

Category is "Accessibility" (see WebControl.AccessKey)

2021-11-19 16:20 UTC, MichaelKetting requested changes

2021-11-19 16:20 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.IntegrationTests/TabbedMenuControlObjectTest.cs
> +    public void TestMenuItemW_WithValidAccessKey ()
```suggestion
    public void TestMenuItem_WithValidAccessKey ()
```

2021-11-19 16:20 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.ControlObjects/TabbedMenuControlObject.cs
> +                  .ToList());
```suggestion
                      .ToList());
```
Sorry, whitespace counting. my bad. Indent of ToList() was originally correct before thsi PR.

2021-11-22 08:11 UTC, MichaelKetting approved these changes

2021-11-22 09:36 UTC, merged