RM-8167: Use DiagnosticMetadataAttributes.Content instead of the Text API to fetch button text
re-motion/Framework pull request #269
Opened 2021-11-23 10:18 UTC by iam-mholle

2021-11-23 11:17 UTC, derlistigelurch approved these changes

2021-11-23 11:54 UTC, MichaelKetting requested changes

2021-11-23 11:54 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.ControlObjects/WebButtonControlObject.cs
> +      return Scope[DiagnosticMetadataAttributes.Content].Trim();
Trim() should not be necessary when we have a dedicated attribute.
```suggestion
      return Scope[DiagnosticMetadataAttributes.Content];
```

2021-11-24 09:13 UTC, MichaelKetting approved these changes

2021-11-24 10:11 UTC, merged