RM-8292: Change WebButton default border color to primary blue
re-motion/Framework pull request #359
Opened 2022-03-21 12:12 UTC by iam-mholle

2022-03-21 12:13 UTC, iam-mholle commented
@MichaelKetting I used the opportunity to remove the `input.webButton` target - no other rules apply to this selector, am I right to assume that it is obsolete? If not, I'll just change it back.

2022-03-21 12:28 UTC, MichaelKetting commented
> @MichaelKetting I used the opportunity to remove the `input.webButton` target - no other rules apply to this selector, am I right to assume that it is obsolete? If not, I'll just change it back.

@iam-mholle Please revert that one. If you set the `WebButton.UseLegacyButton` flag to true, you get the `input` element + the css class.

2022-03-21 12:31 UTC, MichaelKetting requested changes

2022-03-21 12:31 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/WebButton.css
> +  border-color: var(--color-primary);
I think we need to do this in Common.css. The border look&feel is unified for all button elements via Common.css, so the special color applied to buttons needs to be implemented there as well.

2022-03-21 12:32 UTC, iam-mholle commented
> > @MichaelKetting I used the opportunity to remove the `input.webButton` target - no other rules apply to this selector, am I right to assume that it is obsolete? If not, I'll just change it back.
> 
> @iam-mholle Please revert that one. If you set the `WebButton.UseLegacyButton` flag to true, you get the `input` element + the css class.

That means that `primary`/`supplemental` style is not available on the legacy button?

2022-03-21 12:33 UTC, MichaelKetting commented
> That means that primary/supplemental style is not available on the legacy button?

Hmm... yeah, I think we didn't notice that one. Could you please create a ticket for this?

2022-03-25 08:13 UTC, MichaelKetting requested changes

2022-03-28 10:38 UTC, merged