RM-8559 Fix NovaViso Tabs to be left aligned
re-motion/Framework pull request #468
Opened 2022-09-23 10:19 UTC by Frazerus

2022-09-23 11:41 UTC, a-ctor approved these changes

2022-09-23 11:55 UTC, MichaelKetting requested changes

2022-09-23 11:55 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/TabStrip.css
>    flex-grow: 99999;
The changes are applied to the wrong context. TabStrip is used standaline and with TabbedMenu and TabbedMultiView. The changes should only apply to TabbedMenu.

We need to reset the unwanted changes in TabbedMenu while leaving the original for TabStrip and TabbedMultiView.

The first element is the TabbedMenu, the second and third elements are TabbedMultiView and TabStrip. Only the TabbedMenu should be changed in this task.
![image](https://user-images.githubusercontent.com/6972548/191954724-87014e2e-0bb7-4ed1-b36e-ee93fdebad08.png)

2022-09-26 09:07 UTC, MichaelKetting requested changes

2022-09-26 09:07 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/TabbedMenu.css
> +.tabbedMainMenu li, .tabbedSubMenu li
There's a cleaner solution in CSS available: you can use `flex-grow: unset` to clear the not-wanted value. For selector, please use the original selector and prefix with tabbedMainMenu / tabbedSubMenu. That way, the selector weight is better guaranteed.

We should also add the `justify-content: start` attribute to make things more explicit.

By using `display: flex` here, you start a new flexbox, which adds an additional nesting that is not needed and results more in a workaround. The best choice when overriding problematic rules is to find the correct way to remove them (either by unsetting them or by setting a new value that correctly expresses the intention).

Here's also good information on selectors:  https://www.w3schools.com/css/css_selectors.asp & https://www.w3schools.com/cssref/css_selectors.asp
and specificity: https://www.w3schools.com/css/css_specificity.asp

And iniitial/inhertit/unset of values: https://www.w3schools.com/cssref/css3_pr_all.asp

2022-09-28 08:43 UTC, MichaelKetting requested changes

2022-09-28 08:43 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/TabbedMenu.css
> +  justify-content: start;
Something got lost in translation here. The 'justify' needs to be applied to another selector (see ticket). let's do it together.

2022-09-28 10:39 UTC, MichaelKetting approved these changes

2022-09-29 12:06 UTC, merged