RM-8419 TreeNode only clickable on the text
re-motion/Framework pull request #475
Opened 2022-10-06 11:43 UTC by a-ctor

https://re-motion.atlassian.net/browse/RM-8419

Notes:
 - Left and right click are now re-dispatched to the correct element
 - `flex-grow: 1` is still necessary since the dropdownmenu restricts the position according to the element

2022-10-06 14:14 UTC, MichaelKetting requested changes

2022-10-06 14:14 UTC, MichaelKetting commented on Remotion/Web/Core/Res/Themes/NovaViso/HTML/TreeView.css
> +
Is this actually used now that we are using Javascript? The referenced spans already fill the relevant area since they highlight the hover-effect.

2022-10-06 14:14 UTC, MichaelKetting commented on Remotion/Web/ClientScript/Scripts/TreeView.ts
> +          });
Single quotes, please. It's the way most of the re-motion Typescript is written, including in this file.

Historical reason: double-quote is used in C# and when writing attributes in HTML, so using single quotes in Javascript solves the escape-problem.

2022-10-07 07:35 UTC, a-ctor commented on Remotion/Web/ClientScript/Scripts/TreeView.ts
> +        const linkElement = node.querySelector (":scope > .treeViewNodeHead > a[onclick], :scope > .treeViewNodeHeadSelected > a[onclick]") as Nullable<HTMLElement>;
`querySelector` only selects one element so this should be covered? Without marking the a tag there is no 100% reliable way to detect the correct element.

2022-10-07 07:37 UTC, MichaelKetting commented on Remotion/Web/ClientScript/Scripts/TreeView.ts
> +        const linkElement = node.querySelector (":scope > .treeViewNodeHead > a[onclick], :scope > .treeViewNodeHeadSelected > a[onclick]") as Nullable<HTMLElement>;
Ah, yes. only gets the first one anyway. Okay. And no, I wouldn't care enough to select the correct one, just not more than one :)

2022-10-09 13:57 UTC, MichaelKetting approved these changes

2022-10-10 07:54 UTC, merged