RM-8577 Upgrade log4net to 2.0.15
re-motion/Framework pull request #500
Opened 2022-10-20 14:34 UTC by KUJO7

https://re-motion.atlassian.net/browse/RM-8577

2022-10-21 07:02 UTC, a-ctor requested changes

2022-10-21 07:02 UTC, a-ctor commented on Remotion/Web/Test.NetFramework/Web.config
> -        <add name="X-UA-Compatible" value="IE=Edge"/>
reset changes in this file, see other comment.

2022-10-21 07:02 UTC, a-ctor commented on Remotion/ObjectBinding/Web.Test/Web.config
> +    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
reset changes in this file, see other comment.

2022-11-02 07:31 UTC, MichaelKetting approved these changes

2022-11-02 09:39 UTC, a-ctor approved these changes

2022-11-02 11:18 UTC, merged