RM-8698 RemoveRegisterElementForBorderSpans()
re-motion/Framework pull request #584
Opened 2023-01-13 16:07 UTC by KuJo7

https://re-motion.atlassian.net/browse/RM-8698

2023-01-17 08:06 UTC, a-ctor approved these changes

2023-01-17 08:06 UTC, a-ctor commented on Remotion/Web/Core/Utilities/ScriptUtilityExtensions.Obsolete.cs
> +    }
```suggestion
    {
    }
```

2023-01-17 08:15 UTC, MichaelKetting requested changes

2023-01-17 08:15 UTC, MichaelKetting commented on Remotion/Web/Core/Utilities/ScriptUtilityExtensions.Obsolete.cs
> +
`throws new NotSupportedException("IScriptUtility.RegisterElementForBorderSpans() was removed. (Version 4.0.0)");`

2023-01-19 10:37 UTC, MichaelKetting approved these changes

2023-01-19 14:11 UTC, merged