RM-7662: Remove jQuery usages from BocBooleanValue
re-motion/Framework pull request #62
Opened 2021-03-28 12:32 UTC by Stefan-Ilic

https://re-motion.atlassian.net/browse/RM-7662

2021-03-31 16:55 UTC, a-ctor commented on Remotion/ObjectBinding/Web.UnitTests/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRendererTest.cs
> +             + "this.parentNode.querySelector(':scope>a').querySelector(':scope>img'), this.parentNode.querySelectorAll('span')[1], "
We can convert this into a single CSS selector

```suggestion
             + "this.parentNode.querySelector(':scope>a>img'), this.parentNode.querySelectorAll('span')[1], "
```

2021-03-31 16:55 UTC, a-ctor commented on Remotion/ObjectBinding/Web/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRenderer.cs
> +      scriptBuilder.Append ("this.parentNode.querySelector(':scope>a').querySelector(':scope>img')");
Same here

```suggestion
      scriptBuilder.Append ("this.parentNode.querySelector(':scope>a>img')");
```

2021-04-01 07:28 UTC, Stefan-Ilic commented on Remotion/ObjectBinding/Web/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRenderer.cs
> +      scriptBuilder.Append ("this.parentNode.querySelector('input')");
Oh, you're right! It's a shame the tests all still work, though 😂😅

2021-04-06 09:16 UTC, a-ctor approved these changes

2021-04-06 16:06 UTC, MichaelKetting requested changes

2021-04-06 16:06 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web.UnitTests/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRendererTest.cs
> +             + "this.parentNode.querySelector(':scope>input'), " + isRequired.ToString().ToLower() + ", "
```suggestion
             + "this.parentNode.querySelector(':scope > a > img'), this.parentNode.querySelectorAll(':scope>span')[1], "
             + "this.parentNode.querySelector(':scope > input'), " + isRequired.ToString().ToLower() + ", "
```

2021-04-06 16:06 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRenderer.cs
> +      scriptBuilder.Append ("this.parentNode.querySelector(':scope>a')");
```suggestion
      scriptBuilder.Append ("this.parentNode.querySelector(':scope > a')");
```

2021-04-06 16:06 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRenderer.cs
> +      scriptBuilder.Append ("this.parentNode.querySelector(':scope>a>img')");
```suggestion
      scriptBuilder.Append ("this.parentNode.querySelector(':scope > a > img')");
```

2021-04-06 16:06 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRenderer.cs
> +        scriptBuilder.Append ("this.parentNode.querySelectorAll(':scope>span')[1]");
```suggestion
        scriptBuilder.Append ("this.parentNode.querySelectorAll(':scope > span')[1]");
```

2021-04-06 16:06 UTC, MichaelKetting commented on Remotion/ObjectBinding/Web/UI/Controls/BocBooleanValueImplementation/Rendering/BocBooleanValueRenderer.cs
> +      scriptBuilder.Append ("this.parentNode.querySelector(':scope>input')");
```suggestion
      scriptBuilder.Append ("this.parentNode.querySelector(':scope > input')");
```

2021-04-08 12:11 UTC, MichaelKetting approved these changes

2021-04-09 13:36 UTC, merged