RM-7319 (v2.28): Added retry loop for the flaky ResolveBorderElementA test
re-motion/Framework pull request #71
Opened 2021-04-07 13:08 UTC by iam-mholle

https://re-motion.atlassian.net/browse/RM-7319

cherry picked from commit 306de13a331b1de75cdb8b5fd977dc4b5b2a37bc

2021-04-08 08:41 UTC, raffaelfoidl approved these changes

2021-04-08 09:12 UTC, raffaelfoidl approved these changes

2021-04-08 16:50 UTC, MichaelKetting approved these changes

2021-04-08 16:53 UTC, MichaelKetting requested changes

2021-04-08 16:53 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.IntegrationTests/ScreenshotTest.cs
> +      // TODO: Remove when RM-7187 is resolved, use the RetryAttribute provided by NUnit instead.
```suggestion
```

2021-04-08 16:53 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.IntegrationTests/ScreenshotTest.cs
> +      // TODO: Remove when RM-7187 is resolved, use the RetryAttribute provided by NUnit instead.
We don't do a backport of NUnit 3, so there is no need to add the todo comments in the backport

2021-04-10 13:15 UTC, MichaelKetting approved these changes

2021-04-12 10:28 UTC, merged