RM-7283 (v2.28): Added retry loop for the flaky ResolveBorderElementB test
re-motion/Framework pull request #72
Opened 2021-04-07 13:09 UTC by iam-mholle

https://re-motion.atlassian.net/browse/RM-7283

cherry picked from commit 306de13a331b1de75cdb8b5fd977dc4b5b2a37bc

2021-04-08 08:41 UTC, raffaelfoidl approved these changes

2021-04-08 16:51 UTC, MichaelKetting approved these changes

2021-04-08 16:54 UTC, MichaelKetting requested changes

2021-04-08 16:54 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.IntegrationTests/ScreenshotTest.cs
> +      // TODO: Remove when RM-7187 is resolved, use the RetryAttribute provided by NUnit instead.
```suggestion
```

2021-04-08 16:54 UTC, MichaelKetting commented on Remotion/Web/Development.WebTesting.IntegrationTests/ScreenshotTest.cs
> +      // TODO: Remove when RM-7187 is resolved, use the RetryAttribute provided by NUnit instead.
NUnit 3 won't be backported, so we don't need the TODO

2021-04-10 13:15 UTC, MichaelKetting approved these changes

2021-04-14 07:56 UTC, merged