Feature/rm 8637 setting control required true while control enable optional validators false has no effect beyond rendering the required marker
re-motion/Framework pull request #783
Opened 2023-08-02 12:42 UTC by Frazerus

https://re-motion.atlassian.net/browse/RM-8637

2023-08-03 12:27 UTC, KuJo7 approved these changes
Looks fine for me :)

2023-08-03 12:27 UTC, KuJo7 commented on Remotion/ObjectBinding/Web/UI/Controls/BusinessObjectBoundEditableWebControl.cs
remove unused `using Remotion.Web.UI.Controls;`

2023-08-03 16:24 UTC, MichaelKetting requested changes
There's a couple of simplifications we need to do.

2023-08-07 09:05 UTC, MichaelKetting approved these changes
I had some last minute tweaks. Now we just need to split the commits. I think I'll do that quickly.

2023-08-07 09:22 UTC, MichaelKetting approved these changes
Rebase is also done now.

2023-08-07 11:09 UTC, merged