RM-8985 Replace AppConfigBasedSettingsProvider with IoC implementation
re-motion/Framework pull request #902
Opened 2023-10-31 13:28 UTC by a-ctor

https://re-motion.atlassian.net/browse/RM-8985

2023-11-02 14:20 UTC, martin-herwich requested changes

2023-11-02 14:20 UTC, martin-herwich commented on Remotion/Core/Reflection.CodeGeneration.TypePipe/RemotionPipelineRegistry.cs
Clean up using directives.

2023-11-02 14:20 UTC, martin-herwich commented on Remotion/Core/Reflection.CodeGeneration.TypePipe/RemotionPipelineRegistry.cs
> +      var settings = new PipelineSettingsProvider().GetSettings();
I don't understand. The original AppConfigBaseSettingsProvider read its settings from the config file, which could be customized. Why don't we need this any more?

2023-11-03 11:48 UTC, martin-herwich approved these changes

2023-11-03 13:23 UTC, merged

2023-11-14 07:55 UTC, MichaelKetting reviewed
Obso

2023-11-14 07:55 UTC, MichaelKetting commented on Remotion/Core/Reflection.CodeGeneration.TypePipe/Configuration/AppConfigBasedSettingsProvider.obsolete.cs
> +    public bool ForceStrongNaming => throw new NotSupportedException("AppConfigBasedSettingsProvider is no longer supported. (Version 6.0.0)");
The public members with NotSupportedException also get Obsolete attribute.

2023-11-14 07:55 UTC, MichaelKetting commented on Remotion/Core/Reflection.CodeGeneration.TypePipe/IPipelineSettingsProvider.cs
> +  public interface IPipelineSettingsProvider
I prefer to have a seealso-element in the xmldoc listing the implementations. Helps with doc-navigation.

2023-11-14 07:55 UTC, MichaelKetting commented on Remotion/Data/DomainObjects.UnitTests/RemotionTestsPipelineRegistry.cs
> +  public class RemotionTestsPipelineRegistry : DefaultPipelineRegistry
Neceassry. Good choice. Looking forward to deleting them when we drop serialization support.