RM-7635 Document how the TypeScript build infrastructure works
re-motion/Framework pull request #911
Opened 2023-11-09 09:41 UTC by a-ctor

https://re-motion.atlassian.net/browse/RM-7635

2023-11-09 10:12 UTC, Frazerus requested changes

2023-11-09 10:12 UTC, Frazerus commented on Remotion/Web/ClientScript/README.md
> +As previously mentioned, the build outputs are located in `bin/<Configuration>/dist` and there are a few different kind of output files. Only the `*.js` files are actually necessary for downstream pr
```suggestion
There are different kinds of output files generated in the build output directories `bin/<Configuration>/dist`. Only the `*.js` files are necessary for downstream projects, the other file types have other usecases:
```

2023-11-09 10:12 UTC, Frazerus commented on Remotion/Web/ClientScript/README.md
> +References between different TypeScript projects are done using TypeScript's project references. The `Remotion.ObjectBinding.Web.ClientScript` project, for example, has a project reference on `Remoti
```suggestion
References between different TypeScript projects are done using TypeScript's project references. The `Remotion.ObjectBinding.Web.ClientScript` project, for example, has a project reference on `Remotion.Web.ClientScript`, which can be found in all three `tsconfig.json` files. The Debug/Release files reference their respective `tsconfig.json` in the other project. The root "IDE" `tsconfig.json` references the debug version in the other project. This is necessary as it is not possible to reference the other project's "IDE" `tsconfig.json` as it does not emit any output.
```

2023-11-09 10:12 UTC, Frazerus commented on Remotion/Web/ClientScript/README.md
> +For project reference to work there are requirements in the referenced project and the referencing project. The references project must have `"composite": true` and must have a `baseUrl` set. The ref
```suggestion
There are requirements for the referenced and the referencing project for project references to work. The referenced project must have `"composite": true` and must have a `baseUrl` set. The referencing project has the `"references": { "path": "..." }` entry and must also have the MSBuild property `<TypeScriptBuildMode>true</TypeScriptBuildMode>` set.
```

2023-11-16 09:45 UTC, a-ctor commented on Remotion/Web/ClientScript/README.md
> +The `Scripts` folder contains the TypeScript files that are compiled as part of the project. There are regular TypeScript files `*.ts` and TypeScript definition files `*.d.ts`, with the definition fi
Do you mean the `"./Scripts/**/*.js"` include in the `tsconfig.json`? Yeah we could clean that up but I wouldn't do it in this task.

2023-11-17 08:13 UTC, Frazerus commented on Remotion/Web/ClientScript/README.md
> +The `Scripts` folder contains the TypeScript files that are compiled as part of the project. There are regular TypeScript files `*.ts` and TypeScript definition files `*.d.ts`, with the definition fi
Yeah, I didn't see that we had a few other TS tasks lined up as well.

2023-12-04 14:29 UTC, MichaelKetting approved these changes
It looks okay to me. I noticed that I knew everything that's written in there by sight, so I cannot say if someone who isn't aware of these things can start working based on the didactic presentation. Let's assume that this is indeed the case and if martin has to fix some JS next year, we will have a live beta test of the docs :)

2023-12-06 10:57 UTC, merged