RM-7592: Add NRT support in Globalization
re-motion/Framework pull request #98
Opened 2021-05-07 09:11 UTC by iam-mholle

https://re-motion.atlassian.net/browse/RM-7592

2021-05-10 06:25 UTC, MichaelKetting requested changes
I'll re-review after the namespace-references are moved to using-statements.

2021-05-10 06:25 UTC, MichaelKetting commented on Remotion/Globalization/Core/IEnumerationGlobalizationService.cs
> +    bool TryGetEnumerationValueDisplayName ([NotNull] Enum value, [CanBeNull][System.Diagnostics.CodeAnalysis.MaybeNullWhen (false)] out string result);
Please don't use inline namespaces.

2021-05-10 06:25 UTC, MichaelKetting commented on Remotion/Globalization/Core/IMemberInformationGlobalizationService.cs
> +        [System.Diagnostics.CodeAnalysis.MaybeNullWhen (false)] out string result);
Namespace

2021-05-10 08:06 UTC, MichaelKetting requested changes

2021-05-10 09:04 UTC, iam-mholle commented on Remotion/Globalization/Core/Implementation/LocalizedNameProviderBase.cs
> +        [CanBeNull][MaybeNullWhen (false)] out string result)
I thought Jetbrains' `CanBeNull` defines a precondition, meaning that a value with a nullable type could be passed in, which wouldn't necessarily be wrong here. But I agree, it should be removed as it does not add any meaningful information.

2021-05-10 09:05 UTC, iam-mholle commented on Remotion/Globalization/Core/Obsolete/EnumDescription.cs
> +    public static EnumValue[] GetAllValues ([NotNull] Type enumType, [CanBeNull] CultureInfo? culture)
It's not a project in this case, I could only disable NRT in the affected files.

2021-05-10 09:11 UTC, MichaelKetting commented on Remotion/Globalization/Core/Obsolete/EnumDescription.cs
> +    public static EnumValue[] GetAllValues ([NotNull] Type enumType, [CanBeNull] CultureInfo? culture)
ah, true. Missed that one. My bad. Will re-check.

2021-05-10 09:14 UTC, MichaelKetting commented on Remotion/Globalization/Core/Implementation/LocalizedNameProviderBase.cs
> +        [CanBeNull][MaybeNullWhen (false)] out string result)
Correct about CanBeNull. And since it's an out-parameter and always was, CanBeNull at this place is just wrong.

2021-05-19 11:48 UTC, MichaelKetting approved these changes

2021-05-19 12:20 UTC, merged